In [3]:
import pandas as pd

In [6]:
df = pd.read_csv("HousePricePrediction (1).csv")

In [7]:
df.sample(10)

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
2166,2166,20,RL,8696,Inside,1Fam,5,1997,1998,VinylSd,0.0,1418.0,NaN
1945,1945,20,RL,31220,FR2,1Fam,2,1952,1952,BrkFace,0.0,1632.0,NaN
155,155,50,RL,9600,Corner,1Fam,5,1924,1950,Wd Sdng,0.0,572.0,79000.0
2564,2564,20,RL,13108,Inside,1Fam,5,1951,1951,Wd Sdng,0.0,0.0,NaN
2896,2896,20,RL,23580,Inside,1Fam,6,1979,1979,Plywood,0.0,1625.0,NaN
2435,2435,20,RL,7000,Corner,1Fam,6,1961,1961,BrkFace,0.0,0.0,NaN
2885,2885,60,RL,15600,Inside,1Fam,7,1950,1963,Wd Sdng,0.0,1168.0,NaN
1623,1623,60,RL,12961,Inside,1Fam,5,1993,1994,VinylSd,0.0,1152.0,NaN
1243,1243,20,RL,13891,Inside,1Fam,5,2006,2006,VinylSd,0.0,2076.0,465000.0
455,455,20,RL,9600,Inside,1Fam,6,1973,1973,HdBoard,0.0,1242.0,175500.0

Id                 0
MSSubClass         0
MSZoning           4
LotArea            0
LotConfig          0
BldgType           0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
Exterior1st        1
BsmtFinSF2         1
TotalBsmtSF        1
SalePrice       1459
dtype: int64

In [12]:
df["SalePrice"] = df["SalePrice"].fillna(df["SalePrice"].mean())

In [14]:
df.isnull().sum()

Id              0
MSSubClass      0
MSZoning        4
LotArea         0
LotConfig       0
BldgType        0
OverallCond     0
YearBuilt       0
YearRemodAdd    0
Exterior1st     1
BsmtFinSF2      1
TotalBsmtSF     1
SalePrice       0
dtype: int64

In [27]:
df.dropna()

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.00000
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.00000
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.00000
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.00000
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,RM,1936,Inside,Twnhs,7,1970,1970,CemntBd,0.0,546.0,180921.19589
2915,2915,160,RM,1894,Inside,TwnhsE,5,1970,1970,CemntBd,0.0,546.0,180921.19589
2916,2916,20,RL,20000,Inside,1Fam,7,1960,1996,VinylSd,0.0,1224.0,180921.19589
2917,2917,85,RL,10441,Inside,1Fam,5,1992,1992,HdBoard,0.0,912.0,180921.19589
2918,2918,60,RL,9627,Inside,1Fam,5,1993,1994,HdBoard,0.0,996.0,180921.19589

In [28]:
df.isnull().sum()

Id              0
MSSubClass      0
MSZoning        4
LotArea         0
LotConfig       0
BldgType        0
OverallCond     0
YearBuilt       0
YearRemodAdd    0
Exterior1st     1
BsmtFinSF2      1
TotalBsmtSF     1
SalePrice       0
dtype: int64

In [31]:
df["MSZoning"].unique()

array(['RL', 'RM', 'C (all)', 'FV', 'RH', nan], dtype=object)

In [32]:
cols = ['MSZoning', 'LotConfig', 'BldgType', 'Exterior1st']
df = pd.get_dummies(df , columns = cols , drop_first = True,dtype = int)

In [35]:
df.isnull().sum()

Id                     0
MSSubClass             0
LotArea                0
OverallCond            0
YearBuilt              0
YearRemodAdd           0
BsmtFinSF2             1
TotalBsmtSF            1
SalePrice              0
MSZoning_FV            0
MSZoning_RH            0
MSZoning_RL            0
MSZoning_RM            0
LotConfig_CulDSac      0
LotConfig_FR2          0
LotConfig_FR3          0
LotConfig_Inside       0
BldgType_2fmCon        0
BldgType_Duplex        0
BldgType_Twnhs         0
BldgType_TwnhsE        0
Exterior1st_AsphShn    0
Exterior1st_BrkComm    0
Exterior1st_BrkFace    0
Exterior1st_CBlock     0
Exterior1st_CemntBd    0
Exterior1st_HdBoard    0
Exterior1st_ImStucc    0
Exterior1st_MetalSd    0
Exterior1st_Plywood    0
Exterior1st_Stone      0
Exterior1st_Stucco     0
Exterior1st_VinylSd    0
Exterior1st_Wd Sdng    0
Exterior1st_WdShing    0
dtype: int64

In [41]:
df["BsmtFinSF2"] = df["BsmtFinSF2"].fillna(0)
df["BsmtFinSF2"] =  df["BsmtFinSF2"].astype("int64")

In [45]:
df.isnull().sum().sum()

np.int64(0)

In [43]:
df["TotalBsmtSF"] = df["TotalBsmtSF"].fillna(0)
df["TotalBsmtSF"] =  df["TotalBsmtSF"].astype("int64")

In [50]:
df = df.drop("Id",axis = 1)

In [51]:
df.sample(10)

,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,SalePrice,MSZoning_FV,MSZoning_RH,...,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing
2352,60,10625,5,2004,2004,0,1158,180921.19589,1,0,...,0,0,0,0,0,0,0,1,0,0
155,50,9600,5,1924,1950,0,572,79000.00000,0,0,...,0,0,0,0,0,0,0,0,1,0
379,60,8123,5,2000,2000,0,982,179000.00000,0,0,...,0,0,0,0,0,0,0,1,0,0
118,60,12376,5,1990,1990,0,1673,320000.00000,0,0,...,0,0,0,0,1,0,0,0,0,0
2561,70,6720,7,1921,1950,0,585,180921.19589,0,0,...,0,0,0,0,0,0,0,1,0,0
1077,20,15870,5,1969,1969,791,1096,138800.00000,0,0,...,0,0,0,0,0,0,0,1,0,0
2231,20,12890,5,1989,1989,0,1495,180921.19589,0,0,...,0,0,0,0,0,0,0,0,1,0
1481,120,7132,5,2006,2006,0,1370,180921.19589,0,0,...,0,0,0,0,0,0,0,1,0,0
44,20,7945,6,1959,1959,506,1150,141000.00000,0,0,...,0,0,0,0,0,0,0,0,0,0
2554,40,10042,8,1920,1995,278,660,180921.19589,0,0,...,0,0,0,0,0,0,0,0,1,0

In [52]:
x = df.drop("SalePrice",axis = 1)
y = df["SalePrice"]

In [53]:
from sklearn.model_selection import train_test_split

In [54]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 42)

In [55]:
x_train.head()

,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,MSZoning_FV,MSZoning_RH,MSZoning_RL,...,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing
2650,160,2179,5,1976,1976,0,855,0,0,1,...,0,0,0,0,1,0,0,0,0,0
1709,20,7500,5,2006,2007,0,1372,1,0,0,...,0,0,0,0,0,0,0,1,0,0
869,60,9938,5,1993,1994,0,1050,0,0,1,...,0,0,0,1,0,0,0,0,0,0
2355,20,12450,5,2003,2004,0,1094,0,0,1,...,0,0,0,0,0,0,0,1,0,0
2914,160,1936,7,1970,1970,0,546,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [57]:
y_train.head()

2650    180921.19589
1709    180921.19589
869     236000.00000
2355    180921.19589
2914    180921.19589
Name: SalePrice, dtype: float64

In [58]:
from sklearn.linear_model import LinearRegression

In [59]:
model = LinearRegression()

In [60]:
model.fit(x_train,y_train)

LinearRegression()

In [61]:
y_pred = model.predict(x_test)

In [62]:
from sklearn.metrics import r2_score

In [63]:
r2 = r2_score(y_test,y_pred)

In [64]:
r2

0.33632812995189476

accuracy: 2437    1.070925
2470    0.972107
2359    1.183117
789     0.997627
1642    0.894312
          ...
2880    1.139411
2295    0.769082
2222    0.776852
1090    0.782663
542     1.075820
Name: SalePrice, Length: 584, dtype: float64