In [11]:
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_squared_error

In [12]:
df = pd.read_csv("insurance.csv")

In [13]:
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [14]:
x = df.drop("charges" , axis = 1)
y = df["charges"]

In [15]:
x = pd.get_dummies(x,columns = ["region"] , drop_first = True,dtype = int)

In [16]:
x.sample(10)

,age,sex,bmi,children,smoker,region_northwest,region_southeast,region_southwest
534,64,male,40.480,0,no,0,1,0
1307,32,male,28.120,4,yes,1,0,0
215,41,female,37.100,2,no,0,0,1
1135,50,female,28.120,3,no,1,0,0
66,61,female,39.100,2,no,0,0,1
627,33,male,42.460,1,no,0,1,0
1308,25,female,30.200,0,yes,0,0,1
522,51,female,33.915,0,no,0,0,0
24,37,male,28.025,2,no,1,0,0
153,42,female,23.370,0,yes,0,0,0

In [17]:
x["sex"] = x["sex"].map({"female" : 1 , "male": 0})
x["smoker"] = x["smoker"].map({"yes" : 1 , "no": 0})

In [18]:
x["age_smoker"] = x["age"] * x["smoker"]
x["bmi_smoker"] = x["bmi"] * x["smoker"]

In [19]:
x.sample(10)

,age,sex,bmi,children,smoker,region_northwest,region_southeast,region_southwest,age_smoker,bmi_smoker
664,64,1,22.990,0,1,0,1,0,64,22.990
1334,18,1,31.920,0,0,0,0,0,0,0.000
131,61,1,22.040,0,0,0,0,0,0,0.000
975,29,0,22.895,0,1,0,0,0,29,22.895
612,18,1,33.155,0,0,0,0,0,0,0.000
663,18,0,33.660,0,0,0,1,0,0,0.000
620,30,0,31.400,1,0,0,0,1,0,0.000
961,29,1,25.900,0,0,0,0,1,0,0.000
1333,50,0,30.970,3,0,1,0,0,0,0.000
746,34,0,27.000,2,0,0,0,1,0,0.000

In [20]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 42)

In [21]:
lasso_model = Lasso(alpha = 0.5)
lasso_model.fit(x_train,y_train)

Lasso(alpha=0.5)

In [22]:
y_pred = lasso_model.predict(x_test)

In [23]:
 mean_squared_error(y_test,y_pred)

20918648.889825605